
package com.insurance.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.17
 * Fri Nov 13 12:07:26 IST 2015
 * Generated source version: 2.7.17
 */

@XmlRootElement(name = "getProductInformationResponse", namespace = "http://service.insurance.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductInformationResponse", namespace = "http://service.insurance.com/")

public class GetProductInformationResponse {

    @XmlElement(name = "return")
    private com.insurance.beans.Product _return;

    public com.insurance.beans.Product getReturn() {
        return this._return;
    }

    public void setReturn(com.insurance.beans.Product new_return)  {
        this._return = new_return;
    }

}

